language: cpp

env:
  - CXXFLAGS="-march=native"

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse'
        - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse'
        packages:
        - libboost-filesystem-dev
        - libboost-program-options-dev
        - libboost-serialization-dev
        - libboost-system-dev
        - libboost-test-dev
        - libeigen3-dev
        - libflann-dev
        - libode-dev
        - ninja-build
- os: linux
    services:
      - docker
    env: DOCKERFILE="archlinux"

before_install:
  - if [ -n "$DOCKERFILE" ]; then
      docker build -t "$DOCKERFILE" -f "scripts/docker/$DOCKERFILE.Dockerfile" .;
    fi

script:
  - echo "$CXXFLAGS"
  - if [ -n "$DOCKERFILE" ]; then
      docker run -e CXXFLAGS="$CXXFLAGS" "$DOCKERFILE" /bin/sh -c "cmake -G Ninja -DOMPL_REGISTRATION=OFF .. && cmake --build . && ctest";
    else
      mkdir -p build &&
      cd build &&
      cmake -G Ninja -DOMPL_REGISTRATION=OFF .. &&
      cmake --build . &&
      ctest;
    fi
